#!/bin/bash

# Définir le chemin de départ pour la recherche
# Utilisez "." pour représenter le répertoire courant ou spécifiez un chemin spécifique
start_dir="."

# Recherche tous les fichiers nommés 'Makefile' dans l'arborescence de fichiers
# à partir du répertoire spécifié dans START_DIR
find "$start_dir" -type f -name 'Makefile' | while read -r makefile; do
    # Affiche le chemin du Makefile trouvé
    echo "Exécution de 'make clean' pour: $makefile"
    
    # Extrait le répertoire du Makefile trouvé
    makefile_dir=$(dirname "$makefile")
    
    # Change au répertoire du Makefile avant d'exécuter 'make clean'
    (cd "$makefile_dir" && make clean)
done

git add .

exit 0